local Song = {}

Song.Name = "La Marseillaise"
Song.Author = "Rouget de Lisle"
Song.SoundId = "rbxassetid://120439399722201"

Song.Lyrics = {
	{
		time = 0.000,
		segments = {
			{ text = "Introduction", duration = 31.140, narrative = true },
		},
	},
	{
		time = 31.140,
		segments = {
			{ text = "Allons enfant de la patrie", duration = 3.760 },
		},
	},
	{
		time = 34.900,
		segments = {
			{ text = "Le jour de gloire est arrivé", duration = 4.580 },
		},
	},
	{
		time = 39.480,
		segments = {
			{ text = "Contre nous de la tyrannie", duration = 4.270 },
		},
	},
	{
		time = 43.750,
		segments = {
			{ text = "L'étendard sanglant est levé", duration = 4.320 },
		},
	},
	{
		time = 48.070,
		segments = {
			{ text = "L'étendard sanglant est levé", duration = 3.950 },
		},
	},
	{
		time = 52.020,
		segments = {
			{ text = "Entendez-vous dans les campagnes", duration = 4.080 },
		},
	},
	{
		time = 56.100,
		segments = {
			{ text = "Mugir ces féroces soldats?", duration = 5.070 },
		},
	},
	{
		time = 61.170,
		segments = {
			{ text = "Ils viennent jusque dans vos bras", duration = 4.260 },
		},
	},
	{
		time = 65.430,
		segments = {
			{ text = "Égorger vos fils et vos compagnes", duration = 4.700 },
		},
	},
	{
		time = 70.130,
		segments = {
			{ text = "Aux armes, citoyens", duration = 4.270 },
		},
	},
	{
		time = 74.400,
		segments = {
			{ text = "Formez vos bataillons", duration = 4.030 },
		},
	},
	{
		time = 78.430,
		segments = {
			{ text = "Marchez, marchez", duration = 4.800 },
		},
	},
	{
		time = 83.230,
		segments = {
			{ text = "Qu'un sang impur", duration = 3.340 },
		},
	},
	{
		time = 86.570,
		segments = {
			{ text = "Abreuve nos sillons", duration = 5.100 },
		},
	},
	{
		time = 91.670,
		segments = {
			{ text = "Aux armes, citoyens", duration = 4.120 },
		},
	},
	{
		time = 95.790,
		segments = {
			{ text = "Formons nos bataillons", duration = 3.840 },
		},
	},
	{
		time = 99.630,
		segments = {
			{ text = "Marchons, marchons", duration = 4.580 },
		},
	},
	{
		time = 104.210,
		segments = {
			{ text = "Qu'un sang impur", duration = 3.930 },
		},
	},
	{
		time = 108.140,
		segments = {
			{ text = "Abreuve nos sillons", duration = 3.860 },
		},
	},
	{
		time = 112.000,
		segments = {
			{ text = "Pause", duration = 16.040, narrative = true },
		},
	},
	{
		time = 128.040,
		segments = {
			{ text = "Amour sacré de la Patrie", duration = 3.840 },
		},
	},
	{
		time = 131.880,
		segments = {
			{ text = "Conduis, soutiens nos bras vengeurs", duration = 4.560 },
		},
	},
	{
		time = 136.440,
		segments = {
			{ text = "Liberté, Liberté chérie,", duration = 4.350 },
		},
	},
	{
		time = 140.790,
		segments = {
			{ text = "Combats avec tes défenseurs !", duration = 4.250 },
		},
	},
	{
		time = 145.040,
		segments = {
			{ text = "Combats avec tes défenseurs !", duration = 4.040 },
		},
	},
	{
		time = 149.080,
		segments = {
			{ text = "Sous nos drapeaux, que la victoire", duration = 4.020 },
		},
	},
	{
		time = 153.100,
		segments = {
			{ text = "Accoure à tes mâles accents,", duration = 5.080 },
		},
	},
	{
		time = 158.180,
		segments = {
			{ text = "Que nos ennemis expirants", duration = 4.200 },
		},
	},
	{
		time = 162.380,
		segments = {
			{ text = "Voient ton triomphe et notre gloire !", duration = 4.680 },
		},
	},
	{
		time = 167.060,
		segments = {
			{ text = "Aux armes, citoyens", duration = 4.390 },
		},
	},
	{
		time = 171.450,
		segments = {
			{ text = "Formez vos bataillons", duration = 4.140 },
		},
	},
	{
		time = 175.590,
		segments = {
			{ text = "Marchez, marchez", duration = 4.690 },
		},
	},
	{
		time = 180.280,
		segments = {
			{ text = "Qu'un sang impur", duration = 3.850 },
		},
	},
	{
		time = 184.130,
		segments = {
			{ text = "Abreuve nos sillons", duration = 4.780 },
		},
	},
	{
		time = 188.910,
		segments = {
			{ text = "Aux armes, citoyens", duration = 4.210 },
		},
	},
	{
		time = 193.120,
		segments = {
			{ text = "Formons nos bataillons", duration = 3.900 },
		},
	},
	{
		time = 197.020,
		segments = {
			{ text = "Marchons, marchons", duration = 4.710 },
		},
	},
	{
		time = 201.730,
		segments = {
			{ text = "Qu'un sang impur", duration = 3.800 },
		},
	},
	{
		time = 205.530,
		segments = {
			{ text = "Abreuve nos sillons", duration = 3.470 },
		},
	},
	{
		time = 209.000,
		segments = {
			{ text = "Pause", duration = 16.070, narrative = true },
		},
	},
	{
		time = 225.070,
		segments = {
			{ text = "Tremblez, tyrans et vous perfides", duration = 4.220 },
		},
	},
	{
		time = 229.290,
		segments = {
			{ text = "L'opprobre de tous les partis,", duration = 4.880 },
		},
	},
	{
		time = 234.170,
		segments = {
			{ text = "Tremblez ! vos projets parricides", duration = 3.840 },
		},
	},
	{
		time = 238.010,
		segments = {
			{ text = "Vont enfin recevoir leurs prix !", duration = 4.340 },
		},
	},
	{
		time = 242.350,
		segments = {
			{ text = "Vont enfin recevoir leurs prix !", duration = 4.380 },
		},
	},
	{
		time = 246.730,
		segments = {
			{ text = "Tout est soldat pour vous combattre,", duration = 3.720 },
		},
	},
	{
		time = 250.450,
		segments = {
			{ text = "S'ils tombent, nos jeunes héros,", duration = 4.910 },
		},
	},
	{
		time = 255.360,
		segments = {
			{ text = "La terre en produit de nouveaux,", duration = 4.290 },
		},
	},
	{
		time = 259.650,
		segments = {
			{ text = "Contre vous tout prêts à se battre !", duration = 4.810 },
		},
	},
	{
		time = 264.460,
		segments = {
			{ text = "Aux armes, citoyens", duration = 4.320 },
		},
	},
	{
		time = 268.780,
		segments = {
			{ text = "Formez vos bataillons", duration = 3.910 },
		},
	},
	{
		time = 272.690,
		segments = {
			{ text = "Marchez, marchez", duration = 4.810 },
		},
	},
	{
		time = 277.500,
		segments = {
			{ text = "Qu'un sang impur", duration = 3.880 },
		},
	},
	{
		time = 281.380,
		segments = {
			{ text = "Abreuve nos sillons", duration = 4.860 },
		},
	},
	{
		time = 286.240,
		segments = {
			{ text = "Aux armes, citoyens", duration = 4.390 },
		},
	},
	{
		time = 290.630,
		segments = {
			{ text = "Formons nos bataillons", duration = 3.790 },
		},
	},
	{
		time = 294.420,
		segments = {
			{ text = "Marchons, marchons", duration = 4.960 },
		},
	},
	{
		time = 299.380,
		segments = {
			{ text = "Qu'un sang impur", duration = 3.840 },
		},
	},
	{
		time = 303.220,
		segments = {
			{ text = "Abreuve nos sillons", duration = 1.423 },
		},
	},
}

return Song
